
package com.taikang.dic.ltci.common.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version:
 * 2.2
 */
@WebService(name = "LongtermCareService", targetNamespace = "http://server.esb.iengine.medata.com/")
@XmlSeeAlso({ObjectFactory.class})
public interface LongtermCareService {

  /**
   * @param insuredPersonName
   * @param idCardNum
   * @param uniqueNumber
   * @param operator
   * @return returns com.taikang.dic.ltci.common.ws.InsuredInfo
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(
    localName = "queryInsuredInfo",
    targetNamespace = "http://server.esb.iengine.medata.com/",
    className = "com.taikang.dic.ltci.common.ws.QueryInsuredInfo"
  )
  @ResponseWrapper(
    localName = "queryInsuredInfoResponse",
    targetNamespace = "http://server.esb.iengine.medata.com/",
    className = "com.taikang.dic.ltci.common.ws.QueryInsuredInfoResponse"
  )
  public InsuredInfo queryInsuredInfo(
      @WebParam(name = "idCardNum", targetNamespace = "") String idCardNum,
      @WebParam(name = "insuredPersonName", targetNamespace = "") String insuredPersonName,
      @WebParam(name = "uniqueNumber", targetNamespace = "") String uniqueNumber,
      @WebParam(name = "operator", targetNamespace = "") String operator);

  /**
   * @param nurseAmount
   * @return returns com.taikang.dic.ltci.common.ws.NurseAmountDetail
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(
    localName = "getNurseAmountDetail",
    targetNamespace = "http://server.esb.iengine.medata.com/",
    className = "com.taikang.dic.ltci.common.ws.GetNurseAmountDetail"
  )
  @ResponseWrapper(
    localName = "getNurseAmountDetailResponse",
    targetNamespace = "http://server.esb.iengine.medata.com/",
    className = "com.taikang.dic.ltci.common.ws.GetNurseAmountDetailResponse"
  )
  public NurseAmountDetail getNurseAmountDetail(
      @WebParam(name = "nurseAmount", targetNamespace = "") NurseAmount nurseAmount);

  /**
   * @param changhuCard
   * @param registRequest
   * @return returns com.taikang.dic.ltci.common.ws.ErrorReason
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(
    localName = "registNurseInfo",
    targetNamespace = "http://server.esb.iengine.medata.com/",
    className = "com.taikang.dic.ltci.common.ws.RegistNurseInfo"
  )
  @ResponseWrapper(
    localName = "registNurseInfoResponse",
    targetNamespace = "http://server.esb.iengine.medata.com/",
    className = "com.taikang.dic.ltci.common.ws.RegistNurseInfoResponse"
  )
  public ErrorReason registNurseInfo(
      @WebParam(name = "registRequest", targetNamespace = "") NurseInInfo registRequest,
      @WebParam(name = "changhuCard", targetNamespace = "") ChanghuCard changhuCard);

  /**
   * @param insuredPersonName
   * @param idCardNum
   * @param uniqueNumber
   * @param operator
   * @return returns com.taikang.dic.ltci.common.ws.TreatmentState
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(
    localName = "queryNurseTreatment",
    targetNamespace = "http://server.esb.iengine.medata.com/",
    className = "com.taikang.dic.ltci.common.ws.QueryNurseTreatment"
  )
  @ResponseWrapper(
    localName = "queryNurseTreatmentResponse",
    targetNamespace = "http://server.esb.iengine.medata.com/",
    className = "com.taikang.dic.ltci.common.ws.QueryNurseTreatmentResponse"
  )
  public TreatmentState queryNurseTreatment(
      @WebParam(name = "idCardNum", targetNamespace = "") String idCardNum,
      @WebParam(name = "insuredPersonName", targetNamespace = "") String insuredPersonName,
      @WebParam(name = "uniqueNumber", targetNamespace = "") String uniqueNumber,
      @WebParam(name = "operator", targetNamespace = "") String operator);

  /**
   * @param changhuCard
   * @param amountInfo
   * @return returns com.taikang.dic.ltci.common.ws.PersonCostAccount
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(
    localName = "getCostAccount",
    targetNamespace = "http://server.esb.iengine.medata.com/",
    className = "com.taikang.dic.ltci.common.ws.GetCostAccount"
  )
  @ResponseWrapper(
    localName = "getCostAccountResponse",
    targetNamespace = "http://server.esb.iengine.medata.com/",
    className = "com.taikang.dic.ltci.common.ws.GetCostAccountResponse"
  )
  public PersonCostAccount getCostAccount(
      @WebParam(name = "amountInfo", targetNamespace = "") PersonalAmountInfo amountInfo,
      @WebParam(name = "changhuCard", targetNamespace = "") ChanghuCard changhuCard);

  /**
   * @param changhuCard
   * @param uniqueNumber
   * @param operator
   * @return returns com.taikang.dic.ltci.common.ws.SsCard
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(
    localName = "readSSCard",
    targetNamespace = "http://server.esb.iengine.medata.com/",
    className = "com.taikang.dic.ltci.common.ws.ReadSSCard"
  )
  @ResponseWrapper(
    localName = "readSSCardResponse",
    targetNamespace = "http://server.esb.iengine.medata.com/",
    className = "com.taikang.dic.ltci.common.ws.ReadSSCardResponse"
  )
  public SsCard readSSCard(
      @WebParam(name = "changhuCard", targetNamespace = "") ChanghuCard changhuCard,
      @WebParam(name = "uniqueNumber", targetNamespace = "") String uniqueNumber,
      @WebParam(name = "operator", targetNamespace = "") String operator);

  /**
   * @param medicareCode
   * @return returns com.taikang.dic.ltci.common.ws.ErrorReason
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(
    localName = "pushServiceProject",
    targetNamespace = "http://server.esb.iengine.medata.com/",
    className = "com.taikang.dic.ltci.common.ws.PushServiceProject"
  )
  @ResponseWrapper(
    localName = "pushServiceProjectResponse",
    targetNamespace = "http://server.esb.iengine.medata.com/",
    className = "com.taikang.dic.ltci.common.ws.PushServiceProjectResponse"
  )
  public ErrorReason pushServiceProject(
      @WebParam(name = "medicareCode", targetNamespace = "") ServiceProject medicareCode);

  /**
   * @param outInfo
   * @return returns com.taikang.dic.ltci.common.ws.ErrorReason
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(
    localName = "getNurseOutInfo",
    targetNamespace = "http://server.esb.iengine.medata.com/",
    className = "com.taikang.dic.ltci.common.ws.GetNurseOutInfo"
  )
  @ResponseWrapper(
    localName = "getNurseOutInfoResponse",
    targetNamespace = "http://server.esb.iengine.medata.com/",
    className = "com.taikang.dic.ltci.common.ws.GetNurseOutInfoResponse"
  )
  public ErrorReason getNurseOutInfo(
      @WebParam(name = "outInfo", targetNamespace = "") NurseOutInfo outInfo);
}
