
package com.taikang.dic.ltci.common.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version:
 * 2.2
 */
@WebServiceClient(
  name = "LongTermCareServerImplService",
  targetNamespace = "http://server.esb.iengine.medata.com/",
  wsdlLocation = "http://jcpt.tunnel.qydev.com/services/care?wsdl"
)
public class LongTermCareServerImplService extends Service {

  private static final URL LONGTERMCARESERVERIMPLSERVICE_WSDL_LOCATION;
  private static final WebServiceException LONGTERMCARESERVERIMPLSERVICE_EXCEPTION;
  private static final QName LONGTERMCARESERVERIMPLSERVICE_QNAME =
      new QName("http://server.esb.iengine.medata.com/", "LongTermCareServerImplService");

  static {
    URL url = null;
    WebServiceException e = null;
    try {
      url = new URL("http://jcpt.tunnel.qydev.com/services/care?wsdl");
    } catch (MalformedURLException ex) {
      e = new WebServiceException(ex);
    }
    LONGTERMCARESERVERIMPLSERVICE_WSDL_LOCATION = url;
    LONGTERMCARESERVERIMPLSERVICE_EXCEPTION = e;
  }

  public LongTermCareServerImplService() {
    super(__getWsdlLocation(), LONGTERMCARESERVERIMPLSERVICE_QNAME);
  }

  public LongTermCareServerImplService(WebServiceFeature... features) {
    super(__getWsdlLocation(), LONGTERMCARESERVERIMPLSERVICE_QNAME, features);
  }

  public LongTermCareServerImplService(URL wsdlLocation) {
    super(wsdlLocation, LONGTERMCARESERVERIMPLSERVICE_QNAME);
  }

  public LongTermCareServerImplService(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, LONGTERMCARESERVERIMPLSERVICE_QNAME, features);
  }

  public LongTermCareServerImplService(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public LongTermCareServerImplService(
      URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /** @return returns LongtermCareService */
  @WebEndpoint(name = "LongTermCareServerImplPort")
  public LongtermCareService getLongTermCareServerImplPort() {
    return super.getPort(
        new QName("http://server.esb.iengine.medata.com/", "LongTermCareServerImplPort"),
        LongtermCareService.class);
  }

  /**
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *     Supported features not in the <code>features</code> parameter will have their default
   *     values.
   * @return returns LongtermCareService
   */
  @WebEndpoint(name = "LongTermCareServerImplPort")
  public LongtermCareService getLongTermCareServerImplPort(WebServiceFeature... features) {
    return super.getPort(
        new QName("http://server.esb.iengine.medata.com/", "LongTermCareServerImplPort"),
        LongtermCareService.class,
        features);
  }

  private static URL __getWsdlLocation() {
    if (LONGTERMCARESERVERIMPLSERVICE_EXCEPTION != null) {
      throw LONGTERMCARESERVERIMPLSERVICE_EXCEPTION;
    }
    return LONGTERMCARESERVERIMPLSERVICE_WSDL_LOCATION;
  }
}
