#访问路径前缀
restBasePath: /api/v1

#服务启动端口号
server.port: 8086

#系统编码
systemCode: LCPM

#MQ编码
systemCharset: UTF-8

#关闭hystrix
feign.hystrix.enabled: false

#任务发送紧急配置天数
urgentConfig: 2

#任务发送不紧急配置天数
notUrgentConfig: 5

#mybatis的xml映射文件路径
mybatis.mapperLocations: classpath*:com/taikang/dic/ltci/mapper/*.xml

#需要注册别名的POJO类所在包
mybatis.typeAliasesPackage: com.taikang.dic.ltci.model

#基础微服务路径和服务名
feign.system.url: http://localhost:8082
feign.system: ltci-system

#媒体文件微服务地址和服务名
feign.media.file.url: http://localhost:8084
feign.media.file.client: ltci-media-file

#待遇申请微服务地址和服务名
feign.treatment.url: http://localhost:8090
feign.treatment.client: ltci-treatment-application

#机构人员微服务地址
feign.agency.person.url: http://localhost:8087
feign.agency.person.client: ltci-agency-person

#产生待办提醒的定时任务ToDoListController
todoListTiming: 00 59 23 * * ?

#定时重发发送失败的MQ信息的定时任务ScheduleServiceImpl
retryFailMessageTiming: 00 59 23 * * ?

#第三方接口  重新处理协议入住，定时重发ScheduleServiceImpl
reCheckInAndToDRTiming: 0 0 0/5 * * ?

#第三方接口定时重新处理协议退出ScheduleServiceImpl
reCheckOutAndToDRTiming: 0 0 0/5 * * ?

#第三方接口定时重新处理经办的协议退出ScheduleServiceImpl
reUpdateCheckInAndToDRTiming: 0 0 0/5 * * ?

#评估任务发送给专业的Queue和ExChange
ltci.evaluateTask.queue: q.longTermService
ltci.evaluateTask.exchange: x.estimatiionTask
ltci.sendEvaluateTask.messageCode: LTC_TSK_EVA_001

#护理任对象发送给专业的Queue和ExChange
ltci.nursingTaskLongTermService.queue: q.longTermService
ltci.nursingTaskLongTermService.exchange: x.careTarget
ltci.sendNursingTaskLongTermService.messageCode: LTC_TSK_TAC_001

#初评结果接收mq
ltci.firstEvaluate.queue: q.estimationElementaryResult.jingmen
ltci.firstEvaluate.exchange: x.estimationElementaryResult
ltci.firstEvaluate.messageCode: LTC_TSK_EVA_002

#护理对象发送给大数据的Queue和ExChange
ltci.nursingTaskBigData.queue: q.bigData
ltci.nursingTaskBigData.exchange: x.careTarget
ltci.sendNursingTaskBigData.messageCode: LTC_TSK_TAC_001

#出院给专业服务的MQ
ltci.sendCheckOut.queue: q.longTermService
ltci.sendCheckOut.exchange: x.signoutAdmin
ltci.sendCheckOut.messageCode: LTC_TSK_ENC_002

#出院给大数据的MQ
ltci.sendCheckOutBigData.queue: q.bigData
ltci.sendCheckOutBigData.exchange: x.signoutAdmin
ltci.sendCheckOutBigData.messageCode: LTC_TSK_ENC_002

#入住监听
ltci.receiveCheckIn.queue: q.signin.jingmen

#出院监听
ltci.receiveCheckOut.queue: q.signout.jingmen

#数据库连接配置默认连接是开发环境
spring.datasource:
    initialize: false
    url: jdbc:mysql://10.130.206.191:3306/ltci_evaluate_nursing
    username: tklcpm
    password: tklcpm
    
spring.datasource.tomcat:
    max-active: 50
    max-wait: 30000
    test-on-borrow:  true
    max-idle: 10
    min-idle: 5
    test-on-connect: true
    test-on-return: true
    test-while-idle: true
    validation-query: SELECT 1 FROM DUAL
    validation-query-timeout: -1


#rabbitmq连接配置默认连接是开发环境   
spring.rabbitmq:
  host: 10.130.202.57
  port: 5672
  username: longtermcare
  password: longtermcare
  virtualHost: longtermcare

#是否是webservice接口测试，默认不开启
isWebserviceDebug: false

#webservice接口地址
soap.nurse.wsdl.url: http://10.135.45.81/services/care?wsdl

#测试环境  
---
spring.profiles: test
spring.datasource:
    initialize: false
    url: jdbc:mysql://10.130.206.186:3306/ltci_evaluate_nursing
    username: tklcpm
    password: tklcpm
   
spring.rabbitmq:
  host: 10.135.45.77,10.135.45.79
  port: 5672
  username: longtermcare
  password: longtermcare
  virtualHost: longtermcare

#是否是webservice接口测试，默认不开启
isWebserviceDebug: false

#webservice接口地址 
soap.nurse.wsdl.url: http://10.135.45.81/services/care?wsdl

#开发环境  
---
spring.profiles: dev

#mysql 开发环境
spring.datasource:
    initialize: false
    url: jdbc:mysql://10.130.206.191:3306/ltci_evaluate_nursing
    username: tklcpm
    password: tklcpm
    
#rabbitmq 开发环境
spring.rabbitmq:
  host: 10.130.202.57
  port: 5672
  username: longtermcare
  password: longtermcare
  virtualHost: longtermcare

#是否是webservice接口测试，默认不开启
isWebserviceDebug: false

#webservice接口地址
soap.nurse.wsdl.url: http://10.135.45.81/services/care?wsdl
  
#生产环境  
---
spring.profiles: pro

#mysql 生产环境
spring.datasource:
    initialize: false
    url: jdbc:mysql://10.128.128.94:3306/ltci_evaluate_nursing
    username: tklcpm
    password: tklcpm@2ol7

#rabbitmq 生产环境
spring.rabbitmq:
  host: 172.16.70.96,172.16.70.97
  port: 5672
  username: longtermcare
  password: rA20gq
  virtualHost: longtermcare

#是否是webservice接口测试，默认不开启：false; 开启：true
isWebserviceDebug: false

#webservice接口地址
soap.nurse.wsdl.url: http://10.135.45.81/services/care?wsdl

