get:
  tags:
  - application
  summary: 移动端通过参保人身份证、参保人社保卡号、代理人身份证号查询申请状态
  description: 返回申请状态
  operationId: getApplicationState
  parameters: 
    - name: idCard
      in: formData
      description: 用户身份证号
      required: true
      type: string
    - name: insuredPersonName
      in: formData
      description: 用户姓名
      required: true
      type: string      
    - name: securityNumber
      in: formData
      description: 用户社保卡号
      required: true
      type: string
    - name: deputyIdCard
      in: formData
      description: 代理人身份证号
      required: true
      type: string          
               
  responses:
      200:
        description: 查询成功
        schema:
          $ref: "../../ltci-api-v1.yml/#/definitions/RestResponseDTO"
      default:
        description: 其他错误
        schema:
          $ref: "../../ltci-api-v1.yml/#/definitions/RestResponseDTO"








