post:
  tags:
  - treatmentApplication
  summary: 经办人员上传参保人待遇申请的base64格式附件信息
  description: 经办人员上传参保人待遇申请的base64格式附件信息。
  operationId: uploadTreatmentApplicationImgBase64
  parameters: 
    - name: imgBase64
      in: formData
      required: true
      type: string
      description: 上传附件


  responses:
      200:
        description: 附件上传成功
        schema:
          $ref: "../../ltci-portal-api-v1.yml/#/definitions/ResultDTO"
      default:
        description: 其他错误
        schema:
          $ref: "../../ltci-portal-api-v1.yml/#/definitions/ResultDTO"












